import type { LedgerRecord, LedgerTypeTab } from './types'

export const ledgerTypeTabs: LedgerTypeTab[] = [
  { key: 'all', label: '全部类型', tone: 'blue' },
  { key: 'server', label: '服务器台账', tone: 'green' },
  { key: 'app', label: '应用台账', tone: 'sky' },
  { key: 'database', label: '数据库台账', tone: 'cyan' },
  { key: 'middleware', label: '中间件台账', tone: 'orange' },
  { key: 'template', label: '我想要的应用模板', tone: 'indigo' },
  { key: 'finance', label: '金融系统台账', tone: 'blue' },
]

export const ledgerStatusOptions = [
  { label: '已登记', value: '已登记' },
  { label: '待确认', value: '待确认' },
]

export const ledgerDepartmentOptions = [
  { label: '北京交付中心', value: '北京交付中心' },
  { label: '南京运维中心', value: '南京运维中心' },
  { label: '上海交付中心', value: '上海交付中心' },
  { label: '武汉研发中心', value: '武汉研发中心' },
  { label: '信息中心', value: '信息中心' },
]

export const ledgerMoreTypeOptions = [
  { label: '服务器台账', value: 'server' },
  { label: '应用台账', value: 'app' },
  { label: '数据库台账', value: 'database' },
  { label: '中间件台账', value: 'middleware' },
  { label: '我想要的应用模板', value: 'template' },
  { label: '金融系统台账', value: 'finance' },
]

export const ledgerColumns = [
  { title: '名称', key: 'name', dataIndex: 'name', width: 300 },
  { title: '状态', key: 'status', dataIndex: 'status', width: 120 },
  { title: '业务名称', key: 'businessName', dataIndex: 'businessName', width: 180 },
  { title: '所属业务域', key: 'domain', dataIndex: 'domain', width: 120 },
  { title: '环境', key: 'environment', dataIndex: 'environment', width: 90 },
  { title: '网络区域', key: 'networkRegion', dataIndex: 'networkRegion', width: 150 },
  { title: '创建时间', key: 'createdAt', dataIndex: 'createdAt', width: 170 },
  { title: '更新时间', key: 'updatedAt', dataIndex: 'updatedAt', width: 170 },
  { title: '操作', key: 'actions', width: 120, align: 'right' as const },
]

export const ledgerRecords: LedgerRecord[] = [
  {
    id: 1,
    name: '北京标准应用主机A',
    code: 'BJ-APP-001',
    ip: '10.10.1.12',
    type: 'server',
    level: '一级',
    status: '已登记',
    businessName: '北京标准应用',
    domain: '--',
    environment: '生产',
    networkRegion: '服务器区',
    department: '北京交付中心',
    createdAt: '2026-04-16 09:00',
    updatedAt: '2026-04-16 10:00',
    assets: 2,
    services: 1,
    linked: true,
  },
  {
    id: 2,
    name: '南京数据库运维主机',
    code: 'NJ-DB-014',
    ip: '10.20.5.45',
    type: 'database',
    level: '一级',
    status: '已登记',
    businessName: '南京数据库平台',
    domain: '--',
    environment: '生产',
    networkRegion: '运维服务区',
    department: '南京运维中心',
    createdAt: '2026-04-16 09:00',
    updatedAt: '2026-04-16 10:00',
    assets: 2,
    services: 1,
    linked: true,
  },
  {
    id: 3,
    name: '上海标准应用主机B',
    code: 'SH-APP-018',
    ip: '10.30.8.17',
    type: 'app',
    level: '二级',
    status: '已登记',
    businessName: '上海标准应用',
    domain: '--',
    environment: '生产',
    networkRegion: '服务器区',
    department: '上海交付中心',
    createdAt: '2026-04-16 09:00',
    updatedAt: '2026-04-16 10:00',
    assets: 2,
    services: 1,
    linked: true,
  },
  {
    id: 4,
    name: '武汉研发构建主机',
    code: 'WH-CI-003',
    ip: '10.40.12.3',
    type: 'template',
    level: '一级',
    status: '已登记',
    businessName: '武汉研发平台',
    domain: '--',
    environment: '测试',
    networkRegion: '研发服务区',
    department: '武汉研发中心',
    createdAt: '2026-04-16 09:00',
    updatedAt: '2026-04-16 10:00',
    assets: 2,
    services: 1,
    linked: true,
  },
  {
    id: 5,
    name: '信息中心标准计算节点A',
    code: 'INFO-NODE-021',
    ip: '10.60.1.88',
    type: 'server',
    level: '二级',
    status: '已登记',
    businessName: '信息中心计算平台',
    domain: '--',
    environment: '生产',
    networkRegion: '服务器区',
    department: '信息中心',
    createdAt: '2026-04-16 09:00',
    updatedAt: '2026-04-16 10:00',
    assets: 2,
    services: 1,
    linked: true,
  },
  {
    id: 6,
    name: '经营分析计算节点-01',
    code: 'BI-NODE-001',
    ip: '10.70.10.11',
    type: 'finance',
    level: '未挂接',
    status: '待确认',
    businessName: '--',
    domain: '--',
    environment: '生产',
    networkRegion: '--',
    department: '经营分析部',
    createdAt: '2026-04-16 09:34',
    updatedAt: '2026-04-16 09:34',
    assets: 0,
    services: 0,
    linked: false,
  },
  {
    id: 7,
    name: '中间件消息总线节点',
    code: 'MQ-CORE-001',
    ip: '10.80.3.19',
    type: 'middleware',
    level: '二级',
    status: '已登记',
    businessName: '企业消息中台',
    domain: '--',
    environment: '生产',
    networkRegion: '中间件区',
    department: '平台架构组',
    createdAt: '2026-04-17 08:20',
    updatedAt: '2026-04-17 08:40',
    assets: 1,
    services: 3,
    linked: true,
  },
  {
    id: 8,
    name: '应用蓝绿发布模板',
    code: 'TPL-BG-008',
    ip: '10.90.1.8',
    type: 'template',
    level: '一级',
    status: '已登记',
    businessName: '应用模板中心',
    domain: '--',
    environment: '测试',
    networkRegion: '模板服务区',
    department: '平台研发部',
    createdAt: '2026-04-18 11:00',
    updatedAt: '2026-04-18 11:20',
    assets: 1,
    services: 2,
    linked: true,
  },
]
