import type { LedgerRecord, LedgerTypeTab } from './types'

export const ledgerDisplayTotal = 144
export const ledgerTypeCount = 10

export const ledgerTypeTabs: LedgerTypeTab[] = [
  { key: 'all', label: '全部类型', tone: 'blue' },
  { key: 'server', label: '服务器台账', tone: 'green' },
  { key: 'app', label: '应用台账', tone: 'sky' },
  { key: 'database', label: '数据库台账', tone: 'cyan' },
  { key: 'middleware', label: '中间件台账', tone: 'orange' },
  { key: 'template', label: '我想要的应用模板', tone: 'indigo' },
  { key: 'finance', label: '金融系统台账', tone: 'blue' },
]

export const ledgerStatusOptions = [
  { label: '已登记', value: '已登记' },
  { label: '待确认', value: '待确认' },
]

export const ledgerDepartmentOptions = [
  { label: '西安分公司', value: '西安分公司' },
  { label: '成都分公司', value: '成都分公司' },
  { label: '上海分公司', value: '上海分公司' },
  { label: '信息中心', value: '信息中心' },
]

export const ledgerMoreTypeOptions = [
  { label: '存储台账', value: 'storage' },
  { label: '容器台账', value: 'container' },
  { label: '网络台账', value: 'network' },
  { label: '安全台账', value: 'security' },
]

export const ledgerColumns = [
  { title: '账号名称', key: 'name', dataIndex: 'name', width: 280, sorter: true },
  { title: '台账类型', key: 'type', dataIndex: 'typeLabel', width: 170, sorter: true },
  { title: '状态', key: 'status', dataIndex: 'status', width: 110, sorter: true },
  { title: '所属单位', key: 'department', dataIndex: 'department', width: 160, sorter: true },
  { title: '创建人', key: 'creator', dataIndex: 'creator', width: 120, sorter: true },
  { title: '更新时间', key: 'updatedAt', dataIndex: 'updatedAt', width: 170, sorter: true, defaultSortOrder: 'descend' as const },
  { title: '创建时间', key: 'createdAt', dataIndex: 'createdAt', width: 170, sorter: true },
  { title: '操作', key: 'actions', width: 130, align: 'center' as const },
]

export const ledgerRecords: LedgerRecord[] = [
  {
    id: 1,
    name: '报表生成子系统',
    code: 'XA-APP-001',
    ip: '10.20.11.8',
    type: 'app',
    typeLabel: '应用台账',
    typeTone: 'sky',
    status: '已登记',
    department: '西安分公司',
    creator: '吴斌',
    createdAt: '2026-03-26 08:25',
    updatedAt: '2026-04-27 10:38',
    linked: true,
  },
  {
    id: 2,
    name: '仓储管理子系统',
    code: 'CD-APP-006',
    ip: '10.21.16.6',
    type: 'app',
    typeLabel: '应用台账',
    typeTone: 'sky',
    status: '已登记',
    department: '成都分公司',
    creator: '陈明',
    createdAt: '2026-03-26 08:25',
    updatedAt: '2026-04-27 10:38',
    linked: true,
  },
  {
    id: 3,
    name: '上海客户画像ClickHouse',
    code: 'SH-DB-009',
    ip: '10.30.11.20',
    type: 'database',
    typeLabel: '数据库台账',
    typeTone: 'cyan',
    status: '已登记',
    department: '上海分公司',
    creator: '赵强',
    createdAt: '2026-04-16 09:00',
    updatedAt: '2026-04-16 10:00',
    linked: true,
  },
  {
    id: 4,
    name: '上海标准应用主机B',
    code: 'SH-SRV-021',
    ip: '10.30.8.17',
    type: 'server',
    typeLabel: '服务器台账',
    typeTone: 'green',
    status: '已登记',
    department: '上海分公司',
    creator: '赵强',
    createdAt: '2026-04-16 09:00',
    updatedAt: '2026-04-16 10:00',
    linked: true,
  },
  {
    id: 5,
    name: '上海渠道营销大屏',
    code: 'SH-TPL-011',
    ip: '10.30.18.99',
    type: 'template',
    typeLabel: '我想要的应用模板',
    typeTone: 'indigo',
    status: '已登记',
    department: '上海分公司',
    creator: '赵强',
    createdAt: '2026-04-16 09:00',
    updatedAt: '2026-04-16 10:00',
    linked: true,
  },
  {
    id: 6,
    name: '上海缓存代理集群',
    code: 'SH-MW-010',
    ip: '10.30.12.66',
    type: 'middleware',
    typeLabel: '中间件台账',
    typeTone: 'orange',
    status: '已登记',
    department: '上海分公司',
    creator: '赵强',
    createdAt: '2026-04-16 09:00',
    updatedAt: '2026-04-16 10:00',
    linked: true,
  },
  {
    id: 7,
    name: '上海资金归集门户',
    code: 'SH-FIN-008',
    ip: '10.30.19.27',
    type: 'finance',
    typeLabel: '金融系统台账',
    typeTone: 'blue',
    status: '已登记',
    department: '上海分公司',
    creator: '赵强',
    createdAt: '2026-04-16 09:00',
    updatedAt: '2026-04-16 10:00',
    linked: true,
  },
  {
    id: 8,
    name: '信息中心标准计算节点A',
    code: 'INFO-SRV-003',
    ip: '10.60.1.88',
    type: 'server',
    typeLabel: '服务器台账',
    typeTone: 'green',
    status: '已登记',
    department: '信息中心',
    creator: '张伟',
    createdAt: '2026-04-16 09:00',
    updatedAt: '2026-04-16 10:00',
    linked: true,
  },
]
